mod protocol;
mod renderer;
mod session;

use std::io::{self, IsTerminal, Read};

use clap::{Parser, Subcommand};

const A2UI_VERSION: &str = "0.1";
const SCHEMA: &str = include_str!("../schema/a2ui-v0.1.schema.json");

/// a2n — A2UI Protocol native UI renderer for AI agents.
///
/// Reads a JSON form spec (from stdin or as an inline argument), renders a
/// native window, and writes the user's response as JSON to stdout.
/// One JSON in, one JSON out — no chat loop, no web server.
///
/// Run `a2n schema` to print the full input JSON Schema.
#[derive(Parser)]
#[command(
    name = "a2n",
    version,
    about = "A2UI Protocol — collect user input via native UI forms for AI agents",
    long_about = None,
    disable_help_subcommand = true,
)]
struct Cli {
    /// Subcommand: `help` or `schema`.
    #[command(subcommand)]
    command: Option<Command>,

    /// Inline JSON form spec (alternative to piping via stdin).
    #[arg(value_name = "JSON", conflicts_with = "command")]
    json: Option<String>,

    /// Session UUID — keeps the window alive for multi-turn interactions.
    /// On the first call a daemon is spawned; subsequent calls reuse it.
    #[arg(long, value_name = "UUID", conflicts_with = "close")]
    session: Option<String>,

    /// Close a running session window and exit.
    #[arg(long, value_name = "UUID", conflicts_with = "session")]
    close: Option<String>,

    /// [Internal] Run as session daemon — do not call directly.
    #[arg(long, hide = true, requires = "session", conflicts_with = "close")]
    daemon: bool,
}

#[derive(Subcommand)]
enum Command {
    /// Show this help message.
    Help,
    /// Print the A2UI input JSON Schema (v0.1) and exit.
    Schema,
}

fn print_help() {
    println!(
        "\
a2n  —  A2UI Protocol v{A2UI_VERSION}  —  native UI renderer for AI agents

WHAT IT DOES
  AI agents often need structured input from a user (choices, file paths,
  configurations).  Back-and-forth chat is slow and error-prone.  a2n solves
  this: the agent generates a JSON form spec, a2n renders a native window,
  the user fills in the fields, and the answers come back as JSON.

  One JSON in  →  native window  →  one JSON out

USAGE
  a2n [JSON]                     One-shot: inline JSON form spec
  echo '{{...}}' | a2n           One-shot: JSON form spec from stdin
  a2n [JSON] --session <UUID>    Session: keep window open across turns
  a2n --close <UUID>             Close a session window
  a2n schema                     Print the input JSON Schema
  a2n --help                     Show full flag reference
  a2n --version                  Show version

SESSION MODE
  Use --session <UUID> to keep a window alive across multiple agent turns.
  The first invocation spawns a background daemon; subsequent calls update
  the form in the existing window.  Close with: a2n --close <UUID>

SCHEMA
  Run `a2n schema` to see the full JSON Schema for the input format.
  Online: https://a2native.github.io/schema/a2ui-v{A2UI_VERSION}.schema.json

SECURITY
  Every window displays a permanent banner warning the user that the
  interface was generated by an AI agent and that their input will be sent
  to the agent.  Never enter passwords or private keys into a2n forms.

EXAMPLES
  # Simple confirmation dialog
  a2n '{{\"title\":\"Deploy?\",\"components\":[
    {{\"id\":\"ok\",\"type\":\"button\",\"label\":\"Deploy\",\"action\":\"submit\"}},
    {{\"id\":\"no\",\"type\":\"button\",\"label\":\"Cancel\",\"action\":\"cancel\"}}
  ]}}'

  # Multi-field form via stdin
  cat form.json | a2n

  # Multi-turn wizard
  echo '{{...step1...}}' | a2n --session my-wizard-abc123
  echo '{{...step2...}}' | a2n --session my-wizard-abc123
  a2n --close my-wizard-abc123
"
    );
}

fn main() {
    let cli = Cli::parse();

    // ── Subcommands ───────────────────────────────────────────────────────────
    match &cli.command {
        Some(Command::Help) => {
            print_help();
            return;
        }
        Some(Command::Schema) => {
            println!("{SCHEMA}");
            return;
        }
        None => {}
    }

    // ── Close a running session ───────────────────────────────────────────────
    if let Some(uuid) = &cli.close {
        session::send_close(uuid);
        return;
    }

    // ── Daemon mode (spawned internally) ─────────────────────────────────────
    if cli.daemon {
        let uuid = cli.session.as_deref().unwrap_or_else(|| {
            eprintln!("error: --daemon requires --session <UUID>");
            std::process::exit(1);
        });
        renderer::egui_impl::run_daemon(uuid);
        return;
    }

    // ── Resolve JSON input: inline arg takes priority, then stdin ─────────────
    let input_json = if let Some(json) = cli.json {
        json
    } else if !io::stdin().is_terminal() {
        // stdin is a pipe / redirected file — read it
        let mut buf = String::new();
        io::stdin()
            .read_to_string(&mut buf)
            .expect("Failed to read stdin");
        buf
    } else {
        // No JSON provided and stdin is a TTY → show help
        print_help();
        return;
    };

    let input: protocol::A2NInput = serde_json::from_str(&input_json).unwrap_or_else(|e| {
        eprintln!("error: could not parse input JSON: {e}");
        std::process::exit(1);
    });

    // ── Normal / session client mode ─────────────────────────────────────────
    if let Some(uuid) = &cli.session {
        // Try to forward to an already-running session daemon.
        if let Some(output) = session::try_send(uuid, &input) {
            println!("{}", serde_json::to_string(&output).unwrap());
            return;
        }

        // No daemon running yet — clear any stale port file, then spawn.
        session::remove_port(uuid);
        spawn_daemon(uuid);
        if !session::wait_for_daemon(uuid, 10) {
            eprintln!("error: timed out waiting for session daemon to start");
            std::process::exit(1);
        }

        let output = session::try_send(uuid, &input).unwrap_or_else(|| {
            eprintln!("error: failed to connect to session daemon");
            std::process::exit(1);
        });
        println!("{}", serde_json::to_string(&output).unwrap());
    } else {
        // Stateless one-shot mode.
        let renderer = renderer::egui_impl::EguiRenderer::new();
        let output = renderer::Renderer::run(renderer, input);
        println!("{}", serde_json::to_string(&output).unwrap());
    }
}

fn spawn_daemon(uuid: &str) {
    let exe = std::env::current_exe().expect("Cannot determine executable path");
    let mut cmd = std::process::Command::new(&exe);
    cmd.arg("--daemon").arg("--session").arg(uuid);

    // On Windows, detach from the parent console so no extra window pops up.
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const DETACHED_PROCESS: u32 = 0x0000_0008;
        const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
        cmd.creation_flags(DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP);
    }

    cmd.spawn().expect("Failed to spawn session daemon");
}

