mod protocol;
mod renderer;
mod session;

use std::io::{self, IsTerminal, Read};

use clap::{Parser, Subcommand};

const SCHEMA: &str = include_str!("../schema/a2ui-v0.1.schema.json");

/// a2n — native desktop UI renderer for AI agents.
///
/// Reads a JSON form spec (from stdin or as an inline argument), renders a
/// native window, and writes the user's response as JSON to stdout.
/// One JSON in, one JSON out — no chat loop, no web server.
///
/// Run `a2n schema` to print the full input JSON Schema.
#[derive(Parser)]
#[command(
    name = "a2n",
    version,
    about = "Native desktop UI renderer for AI agents — collect user input via native OS forms",
    long_about = None,
    disable_help_subcommand = true,
)]
struct Cli {
    /// Subcommand: `help` or `schema`.
    #[command(subcommand)]
    command: Option<Command>,

    /// Inline JSON form spec (alternative to piping via stdin).
    #[arg(value_name = "JSON", conflicts_with = "command")]
    json: Option<String>,

    /// Session UUID — keeps the window alive for multi-turn interactions.
    /// On the first call a daemon is spawned; subsequent calls reuse it.
    #[arg(long, value_name = "UUID", conflicts_with = "close")]
    session: Option<String>,

    /// Close a running session window and exit.
    #[arg(long, value_name = "UUID", conflicts_with = "session")]
    close: Option<String>,

    /// [Internal] Run as session daemon — do not call directly.
    #[arg(long, hide = true, requires = "session", conflicts_with = "close")]
    daemon: bool,
}

#[derive(Subcommand)]
enum Command {
    /// Show this help message.
    Help,
    /// Print the a2native input JSON Schema and exit.
    Schema,
}

fn print_help() {
    println!(
        "\
a2n  —  native desktop UI renderer for AI agents

WHAT IT DOES
  AI agents often need structured input from a user (choices, file paths,
  configurations).  Back-and-forth chat is slow and error-prone.  a2n solves
  this: the agent generates a JSON form spec, a2n renders a native window,
  the user fills in the fields, and the answers come back as JSON.

  Input priority: inline JSON arg  →  stdin pipe  →  (neither → this help)

USAGE
  a2n [JSON]                     One-shot: inline JSON form spec
  echo '{{...}}' | a2n           One-shot: JSON form spec via stdin pipe
  a2n [JSON] --session <UUID>    Session: keep window open across turns
  a2n --close <UUID>             Close a session window
  a2n schema                     Print the input JSON Schema
  a2n --help                     Show full flag reference
  a2n --version                  Show version

  (Running a2n with no JSON and no stdin pipe shows this help.)

SESSION MODE
  Use --session <UUID> to keep a window alive across multiple agent turns.
  The first invocation spawns a background daemon; subsequent calls update
  the form in the existing window.  Close with: a2n --close <UUID>

SCHEMA
  Run `a2n schema` to see the full JSON Schema for the a2native input format.
  Online: https://a2native.github.io/schema/a2ui-v0.1.schema.json

  a2n auto-detects the input format (priority order):
    1. AG-UI  — TOOL_CALL_START/ARGS/END event stream  → TOOL_CALL_RESULT output
    2. A2UI   — Google A2UI v0.8 surfaceUpdate JSONL   → userAction output
    3. Legacy — a2native flat JSON format              → {{status, values}} output

  AG-UI spec:     https://github.com/ag-ui-protocol/ag-ui
  Google A2UI:    https://github.com/google/a2ui

SECURITY
  Every window displays a permanent banner warning the user that the
  interface was generated by an AI agent and that their input will be sent
  to the agent.  Never enter passwords or private keys into a2n forms.

EXAMPLES
  # Simple confirmation dialog
  a2n '{{\"title\":\"Deploy?\",\"components\":[
    {{\"id\":\"ok\",\"type\":\"button\",\"label\":\"Deploy\",\"action\":\"submit\"}},
    {{\"id\":\"no\",\"type\":\"button\",\"label\":\"Cancel\",\"action\":\"cancel\"}}
  ]}}'

  # Multi-field form via stdin
  cat form.json | a2n

  # Multi-turn wizard
  echo '{{...step1...}}' | a2n --session my-wizard-abc123
  echo '{{...step2...}}' | a2n --session my-wizard-abc123
  a2n --close my-wizard-abc123
"
    );
}

fn main() {
    let cli = Cli::parse();

    // ── Subcommands ───────────────────────────────────────────────────────────
    match &cli.command {
        Some(Command::Help) => {
            print_help();
            return;
        }
        Some(Command::Schema) => {
            println!("{SCHEMA}");
            return;
        }
        None => {}
    }

    // ── Close a running session ───────────────────────────────────────────────
    if let Some(uuid) = &cli.close {
        session::send_close(uuid);
        return;
    }

    // ── Daemon mode (spawned internally) ─────────────────────────────────────
    if cli.daemon {
        let uuid = cli.session.as_deref().unwrap_or_else(|| {
            eprintln!("error: --daemon requires --session <UUID>");
            std::process::exit(1);
        });
        renderer::egui_impl::run_daemon(uuid);
        return;
    }

    // ── Resolve JSON input: inline arg takes priority, then stdin ─────────────
    let input_json = if let Some(json) = cli.json {
        json
    } else if !io::stdin().is_terminal() {
        // stdin is a pipe / redirected file — read it
        let mut buf = String::new();
        io::stdin()
            .read_to_string(&mut buf)
            .expect("Failed to read stdin");
        buf
    } else {
        // No JSON provided and stdin is a TTY → show help
        print_help();
        return;
    };

    // ── Detect format and parse input ────────────────────────────────────────
    //
    // Priority: AG-UI envelope → Google A2UI JSONL → a2native legacy JSON
    //
    // AG-UI: TOOL_CALL_START/ARGS/END stream wrapping the form spec.
    //        Output: TOOL_CALL_RESULT event.
    // A2UI:  Google A2UI surfaceUpdate/beginRendering JSONL.
    //        Output: userAction event.
    // Legacy: a2native-own flat JSON format.
    //        Output: {status, values}.

    enum InputFormat {
        Agui(protocol::agui::AGUIContext),
        Other, // A2UI or legacy — inner_a2ui_ctx distinguishes them
    }

    // For AG-UI we first unwrap the envelope to get the inner form spec.
    let (form_json, fmt): (String, InputFormat) =
        if protocol::agui::is_agui(&input_json) {
            match protocol::agui::parse(&input_json) {
                Ok((args, ctx)) => (args, InputFormat::Agui(ctx)),
                Err(e) => {
                    eprintln!("error: could not parse AG-UI input: {e}");
                    std::process::exit(1);
                }
            }
        } else {
            (input_json.clone(), InputFormat::Other)
        };

    // Now parse the inner form spec (either A2UI or legacy).
    let (input, inner_a2ui_ctx): (protocol::A2NInput, Option<protocol::a2ui::A2UIContext>) =
        if protocol::a2ui::is_a2ui(&form_json) {
            match protocol::a2ui::parse(&form_json) {
                Ok((a2n_input, ctx)) => (a2n_input, Some(ctx)),
                Err(e) => {
                    eprintln!("error: could not parse A2UI form spec: {e}");
                    std::process::exit(1);
                }
            }
        } else {
            let a2n_input: protocol::A2NInput =
                serde_json::from_str(&form_json).unwrap_or_else(|e| {
                    eprintln!("error: could not parse input JSON: {e}");
                    std::process::exit(1);
                });
            (a2n_input, None)
        };

    /// Emit output in the correct envelope format.
    fn emit_output(
        output: protocol::A2NOutput,
        fmt: &InputFormat,
        inner_a2ui_ctx: Option<&protocol::a2ui::A2UIContext>,
    ) {
        // Build the inner result JSON string.
        let inner_json = if let Some(ctx) = inner_a2ui_ctx {
            let a2ui_out = protocol::a2ui::to_output(&output, ctx);
            serde_json::to_string(&a2ui_out).unwrap()
        } else {
            serde_json::to_string(&output).unwrap()
        };

        match fmt {
            InputFormat::Agui(ctx) => {
                let agui_out = protocol::agui::to_output(&inner_json, ctx);
                println!("{}", serde_json::to_string(&agui_out).unwrap());
            }
            InputFormat::Other => {
                println!("{inner_json}");
            }
        }
    }

    // ── Normal / session client mode ─────────────────────────────────────────
    if let Some(uuid) = &cli.session {
        // Try to forward to an already-running session daemon.
        if let Some(output) = session::try_send(uuid, &input) {
            emit_output(output, &fmt, inner_a2ui_ctx.as_ref());
            return;
        }

        // No daemon running yet — clear any stale port file, then spawn.
        session::remove_port(uuid);
        spawn_daemon(uuid);
        if !session::wait_for_daemon(uuid, 10) {
            eprintln!("error: timed out waiting for session daemon to start");
            std::process::exit(1);
        }

        let output = session::try_send(uuid, &input).unwrap_or_else(|| {
            eprintln!("error: failed to connect to session daemon");
            std::process::exit(1);
        });
        emit_output(output, &fmt, inner_a2ui_ctx.as_ref());
    } else {
        // Stateless one-shot mode.
        let renderer = renderer::egui_impl::EguiRenderer::new();
        let output = renderer::Renderer::run(renderer, input);
        emit_output(output, &fmt, inner_a2ui_ctx.as_ref());
    }
}

fn spawn_daemon(uuid: &str) {
    let exe = std::env::current_exe().expect("Cannot determine executable path");
    let mut cmd = std::process::Command::new(&exe);
    cmd.arg("--daemon").arg("--session").arg(uuid);

    // On Windows, detach from the parent console so no extra window pops up.
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const DETACHED_PROCESS: u32 = 0x0000_0008;
        const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
        cmd.creation_flags(DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP);
    }

    cmd.spawn().expect("Failed to spawn session daemon");
}

